### ISSUE TITLE
Can you add maximum game time？

### ISSUE THREAD

**Issue by xiaoxRanRan** [TouchMe-Inc/l4d2_hours_limiter#1]
I need it badly

**Comment by TouchMe-Inc** [comment]
Yes it is possible. I'll leave this ticket open so I don't forget.

**Comment by TouchMe-Inc** [comment]
Ready! Check if it works, then write here so I can close the "issues"

**Comment by xiaoxRanRan** [comment]
> Ready! Check if it works, then write here so I can close the "issues"

I can't compile

**Comment by TouchMe-Inc** [comment]
Make sure you have the [steamworks](https://github.com/hexa-core-eu/SteamWorks) dependency

**Comment by TouchMe-Inc** [comment]
That helped?
